# Generated by Django 5.2.11 on 2026-02-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("DEVELOPER", "Developer"),
                    ("COUNTY_ADMIN", "County Admin"),
                    ("DEPT_MANAGER", "Department Manager"),
                    ("EMPLOYEE", "Employee"),
                ],
                default="EMPLOYEE",
                max_length=32,
            ),
        ),
    ]
