# Generated by Django 5.2.11 on 2026-02-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_inventory_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('CONSUMABLE', 'Consumable'), ('MAINTENANCE', 'Maintenance Record'), ('REQUEST', 'Inventory Request')], max_length=32),
        ),
    ]
