# Generated by Django 5.2.11 on 2026-03-01 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_audit_entity_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('CONSUMABLE', 'Consumable'), ('MAINTENANCE', 'Maintenance Record'), ('REQUEST', 'Inventory Request')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='quantity_on_hand',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='reorder_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
