# Generated by Django 5.2.11 on 2026-03-01 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auditlog_immutable_indexes_consumable_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
